program: VGG_Spectogram_Lightning.py
method: grid
metric:
  name: train_loss
  goal: minimize
parameters:
  lr:
    values: [0.0001]
  test-batch-size:
    values: [16]
  train-batch-size:
    values: [16]
  epochs:
    values: [200]
  seed:
    values: [1234]
  margin:
    values: [1.5, 2]




